export const ADD_POINT = "ADD_POINT";
export const DELETE_POINT = "DELETE_POINT";
export const COMPLETE_POINT = "COMPLETE_POINT";

export const COMPLETE_SKILL = "COMPLETE_SKILL";

export const FETCH_POINT_SKILLS_BEGIN = "FETCH_POINT_SKILLS_BEGIN";
export const FETCH_POINT_SKILLS_SUCCESS = "FETCH_POINT_SKILLS_SUCCESS";
export const FETCH_POINT_SKILLS_FAILURE = "FETCH_POINT_SKILLS_FAILURE";
